--
INSERT IGNORE INTO `command`(`name`,`help`) VALUES
('npcbot add',NULL),
('npcbot command',NULL),
('npcbot command follow',NULL),
('npcbot command follow only',NULL),
('npcbot command nocast',NULL),
('npcbot command nogossip',NULL),
('npcbot command nolongcast',NULL),
('npcbot command rebind',NULL),
('npcbot command standstill',NULL),
('npcbot command stopfully',NULL),
('npcbot command unbind',NULL),
('npcbot command walk',NULL),
('npcbot createnew',NULL),
('npcbot delete',NULL),
('npcbot delete free',NULL),
('npcbot delete id',NULL),
('npcbot distance',NULL),
('npcbot distance attack',NULL),
('npcbot distance attack long',NULL),
('npcbot distance attack short',NULL),
('npcbot dump',NULL),
('npcbot dump load',NULL),
('npcbot dump write',NULL),
('npcbot free',NULL),
('npcbot go',NULL),
('npcbot gs',NULL),
('npcbot hide',NULL),
('npcbot info',NULL),
('npcbot kill',NULL),
('npcbot list spawned',NULL),
('npcbot list spawned free',NULL),
('npcbot log clear',NULL),
('npcbot lookup',NULL),
('npcbot move',NULL),
('npcbot order',NULL),
('npcbot order cast',NULL),
('npcbot order pull',NULL),
('npcbot recall',NULL),
('npcbot recall spawns',NULL),
('npcbot recall teleport',NULL),
('npcbot reloadconfig',NULL),
('npcbot remove',NULL),
('npcbot revive',NULL),
('npcbot sendto',NULL),
('npcbot sendto last',NULL),
('npcbot sendto point',NULL),
('npcbot sendto point set',NULL),
('npcbot set',NULL),
('npcbot set faction',NULL),
('npcbot set owner',NULL),
('npcbot set spec',NULL),
('npcbot show',NULL),
('npcbot spawn',NULL),
('npcbot suicide',NULL),
('npcbot unhide',NULL),
('npcbot useonbot item',NULL),
('npcbot useonbot spell',NULL),
('npcbot vehicle',NULL),
('npcbot vehicle eject',NULL),
('npcbot wp add',NULL),
('npcbot wp del',NULL),
('npcbot wp go',NULL),
('npcbot wp info',NULL),
('npcbot wp links',NULL),
('npcbot wp list',NULL),
('npcbot wp list all',NULL),
('npcbot wp move',NULL),
('npcbot wp setflags',NULL),
('npcbot wp setflags z',NULL),
('npcbot wp setlevels',NULL),
('npcbot wp setlevels z',NULL),
('npcbot wp setlinks',NULL),
('npcbot wp setname',NULL),
('npcbot wp setweights',NULL),
('npcbot wp spawnall',NULL);